name = "toptechreviews-click"
main = "workers/click-tracker.js"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "CLICKS"
database_name = "toptechreviews-clicks"
database_id = "069f27f4-17d4-464b-8583-37c546a6d4d7"

[vars]
REFERIQ_MARKETING_CLICK_URL = "https://referiq.net/api/public/marketing-clicks"

# [[routes]]
# pattern = "toptechreviews.org/api/click*"
# zone_name = "toptechreviews.org"
